const lang = {
    nl: {
        locale: "nl",
        messages: {
            nl: {
                message: {
                    areYouSureToSaveQrCode: "Ben je er zeker van deze QR code te registeren?",
                    authenticate: "Controleren",
                    blank: 'Blanco',
                    chairmanSignedIn: "Voorzitter ingelogd:",
                    confirmation: "Bevestigd",
                    counting: "Tellen",
                    createPassword: "Maak wachtwoord aan",
                    cManualInput: "Handmatige invoer",
                    cObjectionToPilot: "Bezwaar tegen pilot",
                    cPowerOfAttorney: 'Volmacht',
                    cVoterPass: "Kiezerspas",
                    dashboard: "Dashboard",
                    doYoutWantToRegister: 'Wil je dit registeren?',
                    emailAddress: "E-mail adres",
                    enterYourActivationCode: "Voer uw activatie code in",
                    enterYourPassword: "Voer uw wachtwoord in",
                    enterYourPasswordConfirmation: "Bevestig uw wachtwoord",
                    errorEmailCannotBeEmpty: "Email veld kan niet leeg zijn",
                    finishCountingVotes: "Telling afronden",
                    goToDashBoard: "Ga naar dashboard",
                    hello: 'Hallo Wereld',
                    invalid: 'Ongeldig',
                    invalidCredentials: 'Ongeldige toegangsgegevens',
                    manualInput: "Handmatige invoer",
                    menu: "Menu",
                    no: "Tegen",
                    powerOfAttorney: "Volmacht",
                    powerOfAttorneyRegisteredSuccessfully: "Volmacht succesvol geregistreerd",
                    objectionToPilotRegisteredSuccessfully: "Bezwaar succesvol geregistreerd",
                    privateAuthorization: 'Onderhandse volmacht',
                    ok: 'ok',
                    objectionToPilot: "Bezwaar tegen pilot",
                    qrCodeScannedSuccessfully: "QR-code succesvol geregistreerd",
                    scan: "Scan",
                    signedInTellers: "Aangemelde tellers",
                    signedInUsers: "Gebruikers",
                    signin: "Aanmelden",
                    tellerSignIn: "Aanmelden als een teller",
                    transactions: "Transacties",
                    twoFactorAuthentication: "Twee-factor authenticatie",
                    verification: "Verifiëren",
                    vote: "Stem",
                    voterPass: "Kiezerspas",
                    votersPassRegisteredSuccessfyully: "Kiezerspas succesvol geregistreerd",
                    writtenAuthorization: 'Schriftelijke volmacht',
                    yes: "Voor",
                    fillDataFieldsBelow: "Vul onderstaande velden in",
                    totalAmount: "Totaal van",
                    pollingCards: "Stempassen",
                    powerOfAttorneys: "Volmachten",
                    voterPasses: "Kiezerspassen",
                    dataInserted: "Ingevoerde data",
                    continue: "Ga door",
                    tellers: "Tellers",
                    chairman: "Voorzitter",
                    cancel: "Cancel",
                    scanSuccessfull: "scan succesvol",
                    unknownError: "onbekende fout",
                    electionResults: "verkiezingsresultaat",
                    sucessfullySubmited: "succesvol ingediend!",
                    signingOff: "ondertekenen",
                    signOffToSubmitResults: "onderteken om resultaat in te dienen",
                    signOff: "onderteken",
                    submitResult: "resultaat indienen",
                    deviationExplanation: "licht afwijking toe ",
                    unhandledError: "onbehandelde fout",
                    voteRecorded: "stem geregistreerd",
                    verificationAlreadyHappened: "verificatie heeft al plaatsgevonden en was succesvol. Invoer genegeerd.",
                    recountNecessaryBeforeNewVerificationAttempt: "hertellen is noodzakelijk om opnieuw te verifiëren",
                    countingMustBeginFirst: "tellen dient als eerst te beginnen",
                    needsRecount: "hertelling noodzakelijk.",
                    scannedPollingCards: "aantal gescande stempassen",
                    registeredVotes: "aantal geregistreerde stemmen",
                    hash: "hash",
                    dateTime: "datum/tijd",
                    voteType: "stem type",
                    loading: "loading...",
                    teller: "teller",
                    user: "gebruiker",
                    role: "rol",
                    signOut: "afmelden",
                    signOutConfirmation: "bevestiging afmelding",
                    overview: "overzicht",
                    totalRegisteredVotes: "totaal aantal geregistreerde stemmen",
                    admitedVoters: "toegelaten kiezers",
                    collectedPollingCards: "aantal geldige stempassen",
                    collectedPowerOfAttorneys: "aantal geldige volmachtbewijzen",
                    collectedVoterPasses: "aantal geldige kiezerspassen",
                    total: "totaal",
                    deviationAdmitedAndVotes: "afwijking tussen toegelaten kiezers en getelde stemmen",
                    registeredVotes: "geregistreerde stemmen",
                    powerOfAttorneysPrivate: "onderhands volmachtbewijs",
                    powerOfAttorneysWritten: "schriftelijk volmachtbewijs",
                    objectionsToPilot: "bezwaar tegen pilot"
                }
            }
        }
    },

    en: {
        locale: "en",
        messages: {
            en: {
                message: {
                    areYouSureToSaveQrCode: "Are you sure you want to save this QR Code?",
                    authenticate: "authenticate",
                    blank: "Blank",
                    chairmanSignedIn: "chairman signed in:",
                    confirmation: "Confirmation",
                    counting: "counting",
                    createPassword: "create password",
                    cManualInput: "Manual Input",
                    cObjectionToPilot: "Objection to Pilot",
                    cPowerOfAttorney: "Power of Attorney",
                    cVoterPass: "Voter Pass",
                    dashboard: "dashboard",
                    doYoutWantToRegister: "do you want to register a",
                    emailAddress: "e-mail address",
                    enterYourActivationCode: "enter your activation code",
                    enterYourPassword: "enter your password",
                    enterYourPasswordConfirmation: "enter your password confirmation",
                    errorEmailCannotBeEmpty: "email can't be empty",
                    finishCountingVotes: "finish counting",
                    goToDashBoard: "go to dashboard",
                    hello: "Hello World",
                    invalid: "Invalid",
                    invalidCredentials: "Invalid Credentials",
                    manualInput: "manual input",
                    menu: "menu",
                    no: "no",
                    powerOfAttorney: "power of attorney",
                    powerOfAttorneyRegisteredSuccessfully: "Power of Attorney registered successfully",
                    objectionToPilotRegisteredSuccessfully: "Objection registered sucessfully",
                    privateAuthorization: "Private authorization",
                    ok: "Ok",
                    objectionToPilot: "objection to pilot",
                    qrCodeScannedSuccessfully: "QR Code Scanned Successfully.",
                    scan: "scan",
                    signedInTellers: "signed in tellers",
                    signedInUsers: "signed in users",
                    signin: "sign in",
                    tellerSignIn: "sign in as a teller",
                    transactions: "transactions",
                    twoFactorAuthentication: "Two-Factor Authentication",
                    verification: "verification",
                    vote: "vote",
                    voterPass: "voter pass",
                    votersPassRegisteredSuccessfyully: "Voter's pass registered successfully.",
                    writtenAuthorization: "Written authorization",
                    yes: "Yes",
                    fillDataFieldsBelow: "Fill in the fields below",
                    totalAmount: "total amount of",
                    pollingCards: "polling cards",
                    powerOfAttorneys: "power attorneys",
                    voterPasses: "voter passes",
                    dataInserted: "Data inserted",
                    continue: "continue",
                    verifyTheCounting: "Verify the counting",
                    voteType: "vote type",
                    countedVotes: "counted votes",
                    verify: "verify",
                    verifyingPleaseWait: "verifying, please wait...",
                    recount: "recount",
                    tellers: "tellers",
                    chairman: "chairman",
                    cancel: "cancel",
                    scanSuccessfull: "Scan was successfull",
                    unknownError: "Unknown error",
                    electionResults: "election results",
                    sucessfullySubmited: "successfully submitted!",
                    signingOff: "signing off",
                    signOffToSubmitResults: "sign off to submit the results",
                    signOff: "sign off",
                    submitResult: "submit result",
                    deviationExplanation: "deviation explanation",
                    unhandledError: "Unhandled error",
                    voteRecorded: "Vote recorded",
                    verificationAlreadyHappened: "Verification already happened and it was successful. Input disregarded.",
                    recountNecessaryBeforeNewVerificationAttempt: "Recount necessary before new verification attempt.",
                    countingMustBeginFirst: "Counting must begin first.",
                    needsRecount: "Needs Recount.",
                    scannedPollingCards: "scanned polling cards",
                    registeredVotes: "registered votes",
                    hash: "hash",
                    dateTime: "date/time",
                    voteType: "vote type",
                    loading: "loading...",
                    teller: "teller",
                    user: "user",
                    role: "role",
                    signOut: "sign out",
                    signOutConfirmation: " sign out confirmation",
                    overview: "overview",
                    totalRegisteredVotes: "total registered votes",
                    admitedVoters: "Admitted voters",
                    collectedPollingCards: "collected polling cards",
                    collectedPowerOfAttorneys: "collected power of attorneys",
                    collectedVoterPasses: "collected voter passes",
                    total: "total",
                    deviationAdmitedAndVotes: "deviation between admitted voters and counted votes",
                    registeredVotes: "Registered votes",
                    powerOfAttorneysPrivate: "power of attorneys (private)",
                    powerOfAttorneysWritten: "power of attorneys (private)",
                    objectionsToPilot: "objections to pilot"

                }
            }
        }
    }

}